name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
      
    - name: Cache
      id: cache-data
      uses: actions/cache@v1.0.3
      with:
        # A directory to store and save the cache
        path: cache-data
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-data
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm install, build, and test
      if: steps.cache-data.outputs.cache-hit != 'true'
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
